### ISSUE TITLE
[Beacons]: Users can see beacons even after they have expired.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon#20]
Users can see beacons even after they have expired in your beacon section.

Expected behaviour can be: 
    1. Either make a new tab showing expired beacons,
    2. Do not show expired beacons entirely,
    3. Show expired beacons at the very last in your beacons section.

I would like to work on this issue.

**Comment by nb9960** [comment]
Expired beacons were intended to be displayed so that one could view the route.
Along with 3rd (i.e., Show expired beacons at the very last in your beacons section) other changes that need to be done w.r.t this:
- No streams should be running (including the one that tracks location)
- If the user tries to share a URL or shortcode or if the user tries to join the expired beacon, a snackbar should appear displaying 'beacon has expired.'
Other than this, if any other change should be made, then feel free to mention it. Assigning this to you!
